name: capstone
dependencies:
- python=3
- jupyter
- numpy
- pandas
- matplotlib
- plotly
- scikit-learn
- statsmodels
- flake8
- matplotlib
- nltk
- plotly
- geopandas
- fiona
- statsmodels
- seaborn
