name: capstone
dependencies:
- python=3
- jupyter
- numpy
- pandas
- matplotlib
- plotly
- scikit-learn
- statsmodels
- flake8
- tinytex
- plotnine
- matplotlib
- nltk
- plotly
- plotly-express
- geopandas
- fiona
- sklearn
- statsmodels
- seaborn
